# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

 

# Add Maintainer Info
LABEL maintainer="nnallapu35@gmail.com"

 

# Add a volume pointing to /tmp
VOLUME /tmp

 

# Make port 8080 available to the world outside this container
EXPOSE 8080

 

# The application's jar file
ARG JAR_FILE=target/loadgenerator-demo-2.3.1.RELEASE.jar

 

# Add the application's jar to the container
ADD ${JAR_FILE} springboot-demo.jar

 

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Dspring.kafka.bootstrap-servers=kafka:9092", "-jar", "/springboot-demo.jar"]